default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: andy

development:
  <<: *default
  database: another_cuke_rails_development

test:
  <<: *default
  database: another_cuke_rails_test

